[package]
name = "av-format"
description = "Multimedia format demuxing and muxing"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
license = "MIT"

[dependencies]
failure = "0.1.1"
log = "0.4"

[dependencies.av-data]
path = "../data"
version = "*"
