[package]
name = "av-format"
description = "Multimedia format demuxing and muxing"
version = "0.4.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
license = "MIT"
edition = "2021"
repository = "https://github.com/rust-av/rust-av"

[dependencies]
log = "0.4.6"
thiserror = "1.0"
av-data = "0.3.0"
