[package]
name = "av-bitstream"
description = "Simple bit writer/reader"
version = "0.1.1"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
license = "MIT"
repository = "https://github.com/rust-av/rust-av"
edition = "2018"

[dependencies]
err-derive = "0.2.3"
num-traits = "0.2.8"

[dev-dependencies]
assert_matches = "1.3.0"
