[package]
name = "av-codec"
description = "Multimedia format decoding and encoding"
version = "0.3.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
license = "MIT"
repository = "https://github.com/rust-av/rust-av"
edition = "2021"

[dependencies]
av-data = "0.4.0"
num-rational = "0.4.0"
