[package]
name = "av-codec"
description = "Multimedia format decoding and encoding"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]

[dependencies]
num-rational = "0.1"
failure = "0.1.1"

[dependencies.av-data]
path = "../data"
version = "*"
